### ISSUE TITLE
Add Tests for the remaining services

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/gitbeaker#51]
So I've been thinking about finally getting started on testing for this library but im a little unsure of how to go about doing so. Usually I would write tests to validate the logic of each of the functions but in this case, the functions are just api calls to gitlab. 

Is there a way to write tests to ensure these endpoints are still supported without say, creating a dummy gitlab account for testing?

**Comment by arsdehnel** [comment]
Perhaps a `docker-compose`-based approach where a dockerized GitLab is spun up along with the app and then run some superagent tests again it or something?

**Comment by jdalrymple** [comment]
I really like that idea! Ill look into that this week

**Comment by jdalrymple** [comment]
starting working on this in the gitlabci branch :)

**Comment by jdalrymple** [comment]
Anyone know of any preconfigured gitlab docker images? Somehting we can spin up to run api calls agasint?

**Comment by arsdehnel** [comment]
They publish their own images as part of their release process.  

https://docs.gitlab.com/omnibus/docker/

We're using the EE images but I'm sure the CE ones are just fine too.

**Comment by jdalrymple** [comment]
Was just looking into it, though im a lil slow, still have lots to learn about how docker compose works exactly. I have a branch with a simple travis ci file (gitlabci) but besides that not much has been done. I've also been experimenting on docker compose files like:

```
version: '3' 
services: 
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
```

But im still unsure where to put the test calls. I've seen examples of it being in the docker compose file as a separate service , ive also seen it as part of the ci file (like inside the travisci.yml file).  If you have any ideas im super down to learn!

Ill push what i have done so far!
